# Generated by Django 2.2.6 on 2019-12-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
