# Generated by Django 2.2.6 on 2019-12-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testStore', '0002_auto_20191210_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='size',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
